version: '3.8'

services:
  spring-boot-app:
    image: tts-app:latest
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      #AWS_REGION: ${AWS_REGION}
 #   depends_on:
 #     - localstack

 # localstack:
 #   image: localstack/localstack
 #   ports:
 #     - "4566:4566"
 #   environment:
 #     - SERVICES=s3
